### ISSUE TITLE
Use baryluk Parser to get daily data

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/covid19_ch#13]
See: https://github.com/openZH/covid_19/issues/68 for the great scrapers by @baryluk

https://github.com/baryluk/covid_19/tree/master/scrapers and https://github.com/baryluk/covid_19/tree/master/scripts

**Comment by zdavatz** [comment]
@baryluk scraper now work much better
```
~/.software/covid_19/scrapers> ./meta_scrape.sh 
AG 2020-03-25T15:15     319       2 OK 2020-03-26T10:44:23+01:00 https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp
AI 2020-03-28T17:00       9       - OK 2020-03-26T10:44:23+01:00 https://www.ai.ch/themen/gesundheit-alter-und-soziales/gesundheitsfoerderung-und-praevention/uebertragbare-krankheiten/coronavirus
AR 2020-03-26T09:00      40       2 OK 2020-03-26T10:44:23+01:00 https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/
BE 2020-03-26T          660       7 OK 2020-03-26T10:44:24+01:00 https://www.besondere-lage.sites.be.ch/besondere-lage_sites/de/index/corona/index.html
BL 2020-03-25T          341       5 OK 2020-03-26T10:44:24+01:00 https://www.statistik.bl.ch/files/sites/Grafiken/COVID19/Grafik_COVID19_BL_Linie.htm
BS 2020-03-25T10:00     466       - OK 2020-03-26T10:44:24+01:00 https://www.gd.bs.ch/, https://www.gd.bs.ch//nm/2020-tagesbulletin-coronavirus-466-bestaetigte-faelle-im-kanton-basel-stadt-gd.html
GE 2020-03-25T12:00    1604      15 OK 2020-03-26T10:44:25+01:00 https://www.ge.ch/document/point-coronavirus-maladie-covid-19/telecharger
GL 2020-03-25T13:30      40       - OK 2020-03-26T10:44:25+01:00 https://www.gl.ch/verwaltung/finanzen-und-gesundheit/gesundheit/coronavirus.html/4817
GR 2020-03-26T          373       9 OK 2020-03-26T10:44:26+01:00 https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/Seiten/Start.aspx
JU 2020-03-25T18:00      78       - OK 2020-03-26T10:44:26+01:00 https://www.jura.ch/fr/Autorites/Coronavirus/Accueil/Coronavirus-Informations-officielles-a-la-population-jurassienne.html
LU 2020-03-25T11:00     228       - OK 2020-03-26T10:44:26+01:00 https://gesundheit.lu.ch/themen/Humanmedizin/Infektionskrankheiten/Coronavirus
NE 2020-03-25T14:00     256       2 OK 2020-03-26T10:44:27+01:00 https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Pages/Coronavirus.aspx
NW 2020-03-25T15:30      44       0 OK 2020-03-26T10:44:27+01:00 https://www.nw.ch/gesundheitsamtdienste/6044
OW 2020-03-25T           27       - OK 2020-03-26T10:44:28+01:00 https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962
SG 2020-03-26T          280       1 OK 2020-03-26T10:44:28+01:00 https://www.sg.ch/tools/informationen-coronavirus.html
SH 2020-03-26T07:00      35       - OK 2020-03-26T10:44:28+01:00 https://sh.ch/CMS/content.jsp?contentid=3209198&language=DE&_=1584807070095
SO 2020-03-26T00:00     141       1 OK 2020-03-26T10:44:28+01:00 https://corona.so.ch/
SZ 2020-03-25T           99       - OK 2020-03-26T10:44:29+01:00 https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948
TG 2020-03-25T           96       - OK 2020-03-26T10:44:29+01:00 https://www.tg.ch/news/fachdossier-coronavirus.html/10552
TI 2020-03-26T08:00    1401      67 OK 2020-03-26T10:44:29+01:00 https://www4.ti.ch/dss/dsp/covid19/home/
UR 2020-03-24T12:00      25       - OK 2020-03-26T10:44:30+01:00 https://www.ur.ch/themen/2920
Error: Unknown date/time format: Date\tHospitalisations
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 177, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 143, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: Date\tHospitalisations

VD - - - FAILED 2020-03-26T10:44:30+01:00
VS 2020-03-25T          651      14 OK 2020-03-26T10:44:30+01:00 https://www.vs.ch/de/web/coronavirus
ZG 2020-03-26T08:00      87       0 OK 2020-03-26T10:44:30+01:00 https://www.zg.ch/behoerden/gesundheitsdirektion/amt-fuer-gesundheit/corona
ZH 2020-03-25T09:30    1363       7 OK 2020-03-26T10:44:30+01:00 https://gd.zh.ch/internet/gesundheitsdirektion/de/themen/coronavirus.html
```

**Comment by zdavatz** [comment]
https://github.com/zdavatz/covid19_ch/issues/13
